Create CONTRIBUTING.md
eeue56/SlideShower pull request #4
Opened 2016-12-08 15:01 UTC by danprince

Ticking off the main points that new contributors need to be mindful of for this project.

2016-12-08 15:45 UTC, eeue56 commented on CONTRIBUTING.md
> +Enhancements should be sent by Royal Mail First Class Recorded Delivery to: P. B. Butcher, 2 Patterdale, Cumbria, CA32 9FS.
@PButcher can you confirm that the house martin has flown the nest?

2016-12-08 15:47 UTC, eeue56 commented on CONTRIBUTING.md
> +* Summon Richard Stallman through a non-free overhead projector
I believe the correct terminology is to "force lift".

2016-12-08 15:48 UTC, eeue56 commented on CONTRIBUTING.md
> +Bugs should be reported through the internal JIRA instance.
I believe the correct first step is to generate a PDF from Latex in order to report bugs. Then they will be transferred by less important people into JIRA. Also, ensure to pronounce JIRA as `gye-ra`

2016-12-08 15:49 UTC, eeue56 commented on CONTRIBUTING.md
> +A descriptive commit message should also be enjoyable and insightful to read. For this project, we're going with haiku commits.
I prefer thoughtprovoking to insightful commit messsages

2016-12-08 15:49 UTC, eeue56 commented on CONTRIBUTING.md
> +Going forward we'll be using the [Yay macro library](https://github.com/marcioAlmada/yay) so that we can transpile Elm into macroized PHP for the backend.
This is the only reasonable stack for a project of this quality

2016-12-08 15:50 UTC, eeue56 commented on CONTRIBUTING.md
> +Documentation should be submitted as rasterized PNGs using Comic Sans Neue as the font. For a guide on getting started with our documentation editor, check out [this video](https://www.youtube.com/wa
Please ensure that all web development assignments are submitted as screenshots drawn in paint only.

2016-12-08 15:55 UTC, eeue56 commented on CONTRIBUTING.md
> +## List Of Forbidden Songs
I believe the correct terminology is "vox populi"

2016-12-08 16:59 UTC, subsidel requested changes

2016-12-08 16:59 UTC, subsidel commented on CONTRIBUTING.md
> +In order to stick to the good parts of JavaScript, we'll be using an eslint config setup to ignore all language constructs and standard library, other than ES6 Symbols, `with`, `do..for`, `let` and `
Could you add a line about the javascript libraries? Something along the lines of that we will be transitioning away from using JavaCoding to [Scala.js](https://www.scala-js.org/) with [JSXQuery](https://www.npmjs.com/package/jsxquery)?

2017-02-05 22:54 UTC, closed without merging

2017-02-06 00:36 UTC, PButcher commented on CONTRIBUTING.md
> +Enhancements should be sent by Royal Mail First Class Recorded Delivery to: P. B. Butcher, 2 Patterdale, Cumbria, CA32 9FS.
How come I only just saw this... :'D